apiVersion: v1
kind: Pod
metadata: 
  name: short-app
  label: 
    components: frontent # пара ключ/значение, может быть любыми
spec:
  containers: 
    - name: short-app
      image: antonlarichev/short-app
      ports: 
        - containerPort: 80
      resources: 
        limits:
          memory: "128Mi"
          cpu: "500m" # пол процессора
      